[build]
  command = "npm run build"  # Jika Anda memiliki script build, jika tidak bisa diabaikan
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"  # Lokasi fungsi serverless Anda
